# Generated by Django 3.1.7 on 2021-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='d5nfqcfi6x', max_length=200),
        ),
    ]
