# Generated by Django 3.1.7 on 2021-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azmoon',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='08xgw69xok', max_length=200),
        ),
    ]
