# Generated by Django 3.1.7 on 2021-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('participant_number', models.IntegerField(default=0)),
                ('azmoon_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='azmoon',
            name='azmoonclass',
            field=models.ManyToManyField(blank=True, to='formapp.Class'),
        ),
        migrations.AddField(
            model_name='participant',
            name='partclass',
            field=models.ManyToManyField(blank=True, to='formapp.Class'),
        ),
    ]
