# Generated by Django 3.1.7 on 2021-09-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azmoon',
            name='showable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='ugif35ny3b', max_length=200),
        ),
    ]
