# Generated by Django 3.1.7 on 2021-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='qg8j7cq8s4', max_length=200),
        ),
    ]
