# Generated by Django 3.1.7 on 2021-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='pmz1byhfx4', max_length=200),
        ),
    ]
