# Generated by Django 3.1.7 on 2021-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210914_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='bqc5i1skng', max_length=200),
        ),
    ]
