# Generated by Django 3.1.7 on 2021-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210902_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='n83i9ujtus', max_length=200),
        ),
    ]
