# Generated by Django 3.1.7 on 2021-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210831_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='30xx5ok64w', max_length=200),
        ),
    ]
