# Generated by Django 3.1.7 on 2021-08-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210808_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Q_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='Q_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='azmoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.azmoon'),
        ),
    ]
