# Generated by Django 3.1.7 on 2021-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20210904_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='o3pf452yi1', max_length=200),
        ),
    ]
