# Generated by Django 3.1.7 on 2021-08-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20210831_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='3yfwm0d9lr', max_length=200),
        ),
    ]
