# Generated by Django 3.1.7 on 2021-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20210903_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='gjn54zh64o', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Q_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
