# Generated by Django 3.1.7 on 2021-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20210808_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='azmoon',
        ),
        migrations.AddField(
            model_name='question',
            name='azmoon',
            field=models.ManyToManyField(blank=True, null=True, to='formapp.Azmoon'),
        ),
    ]
