# Generated by Django 3.1.7 on 2021-09-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20210904_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='dyukwossc4', max_length=200, unique=True),
        ),
    ]
