# Generated by Django 3.1.7 on 2021-08-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20210901_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='2cp59qi5so', max_length=200),
        ),
    ]
