# Generated by Django 3.1.7 on 2021-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20210916_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azmoon',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='azmoon',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='i6gdf2ujon', max_length=200),
        ),
    ]
