# Generated by Django 3.1.7 on 2021-08-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20210808_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='azmoon',
        ),
        migrations.AddField(
            model_name='question',
            name='azmoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.azmoon'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('goz', 'chand gozineh ee'), ('tash', 'tashrihi')], max_length=20, null=True),
        ),
    ]
