# Generated by Django 3.1.7 on 2021-08-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='azmoon',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='formapp.Participant'),
        ),
    ]
