# Generated by Django 3.1.7 on 2021-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20210905_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='clcs8lei8i', max_length=200),
        ),
    ]
