# Generated by Django 3.1.7 on 2021-09-06 04:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_auto_20210906_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azmoon',
            name='end_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azmoon',
            name='start_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='2iw6kom4hf', max_length=200),
        ),
    ]
