# Generated by Django 3.1.7 on 2021-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_auto_20210916_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azmoon',
            old_name='isactive',
            new_name='isactive_natijeh',
        ),
        migrations.AddField(
            model_name='azmoon',
            name='isactive_score_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='bgpgd1bzg9', max_length=200),
        ),
    ]
