# Generated by Django 3.1.7 on 2021-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20210808_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='azmoon',
            name='Question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='azmoon',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='azmoon',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
