# Generated by Django 3.1.7 on 2021-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_auto_20210808_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azmoon',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='azmoon',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
