# Generated by Django 3.1.7 on 2021-09-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_auto_20210906_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='d5j7h3rmi2', max_length=200),
        ),
    ]
