# Generated by Django 3.1.7 on 2021-08-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_auto_20210808_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azmoon',
            name='participant',
            field=models.ManyToManyField(blank=True, to='formapp.Participant'),
        ),
        migrations.AlterField(
            model_name='question',
            name='azmoon',
            field=models.ManyToManyField(blank=True, to='formapp.Azmoon'),
        ),
    ]
