# Generated by Django 3.1.7 on 2021-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_auto_20210810_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='semat',
            field=models.CharField(choices=[('Ostad', 'Ostad'), ('daneshamoz', 'daneshamoz')], default='daneshamoz', max_length=200),
        ),
    ]
