# Generated by Django 3.1.7 on 2021-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_auto_20210812_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
