# Generated by Django 3.1.7 on 2021-09-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_auto_20210906_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='ikp035qq1t', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Q_image',
            field=models.ImageField(default='questions_image/8.jpeg', upload_to='questions_image'),
        ),
    ]
