# Generated by Django 3.1.7 on 2021-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_auto_20210906_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='gchxq6xogz', max_length=200),
        ),
    ]
