# Generated by Django 3.1.7 on 2021-09-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_auto_20210906_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default='cb975u5c7e', max_length=200),
        ),
    ]
