# Generated by Django 3.1.7 on 2021-08-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_auto_20210812_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
