# Generated by Django 3.1.7 on 2021-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_remove_participant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
