# Generated by Django 3.1.7 on 2021-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_auto_20210812_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
