# Generated by Django 3.1.7 on 2021-08-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0021_auto_20210812_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
