# Generated by Django 3.1.7 on 2021-08-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0022_auto_20210812_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
