# Generated by Django 3.1.7 on 2021-08-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0023_auto_20210812_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
