# Generated by Django 3.1.7 on 2021-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0025_auto_20210812_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(default='گزینه 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(default='گزینه 2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(default='گزینه 3', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(default='گزینه 4', max_length=200, null=True),
        ),
    ]
