# Generated by Django 3.1.7 on 2021-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0026_auto_20210812_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Q_text',
            field=models.TextField(),
        ),
    ]
